// app/privacy/page.tsx
import LegalDocLayout, { type LegalSection } from '@/components/legal/LegalDocLayout'

export const metadata = { title: 'Privacy Policy — EarnGro' }

const sections: LegalSection[] = [
  {
    id: 'introduction',
    heading: 'Introduction',
    content: (
      <>
        <p><strong>EarnGro</strong> ("we," "us," or "our") provides an AI-powered career growth platform, including resume building and analysis, AI-driven career assessments, interview preparation, and related career-development tools (the "Service"). This Privacy Policy explains what personal information we collect, how we use it, who we share it with, and the rights you have over your information.</p>
        <p>This Policy applies to all users of the Service, regardless of where you are located, and is designed to meet the requirements of applicable privacy laws, including the EU General Data Protection Regulation ("GDPR"), the UK GDPR, the California Consumer Privacy Act as amended by the California Privacy Rights Act ("CCPA/CPRA"), and India's Digital Personal Data Protection Act, 2023 ("DPDP Act").</p>
        <p>By using the Service, you acknowledge that you have read this Privacy Policy. Where required by law, we will ask for your explicit consent before processing certain categories of information.</p>
      </>
    ),
  },
  {
    id: 'information-we-collect',
    heading: 'Information We Collect',
    content: (
      <>
        <p><strong>Information you provide directly:</strong></p>
        <table>
          <tbody>
            <tr><td>Account information</td><td>Name, email address, password (hashed), profile photo</td></tr>
            <tr><td>Resume and career data</td><td>Resume/CV content, work experience, education, skills, certifications, professional summaries</td></tr>
            <tr><td>Career assessment responses</td><td>GrowDNA assessment answers, self-rated skills, career goals</td></tr>
            <tr><td>Compensation information</td><td>Current salary, target salary, salary history you choose to provide</td></tr>
            <tr><td>Interview data</td><td>Your responses during AI mock interviews, recordings (if enabled)</td></tr>
            <tr><td>Portfolio and social links</td><td>LinkedIn profile URL, portfolio links you choose to add</td></tr>
            <tr><td>Payment information</td><td>Billing name and address — full card details are handled directly by our payment processor and not stored on our servers</td></tr>
            <tr><td>Uploaded files</td><td>PDF/DOCX resume files and other documents you choose to upload</td></tr>
          </tbody>
        </table>
        <p><strong>Information collected automatically:</strong> device information (IP address, browser, OS), usage data, cookies (see our Cookie Policy), and server logs.</p>
        <p><strong>Information generated by the platform:</strong> AI-generated resume rewrites and optimized content, ATS compatibility scores, career roadmaps, skill-gap analyses, interview feedback, and computed metrics such as your Hiring Readiness Score and Career Health Score.</p>
        <p><strong>Information from third parties:</strong> if you sign in using a third-party account (e.g., Google), we receive basic profile information from that provider, subject to your permissions with them.</p>
      </>
    ),
  },
  {
    id: 'how-we-use',
    heading: 'How We Use Your Information',
    content: (
      <>
        <p>We use your information to create and manage your account, provide the core features of the Service, process payments and manage subscriptions and credit balances, communicate with you about your account and (with consent, where required) marketing, improve and develop the Service, detect and prevent fraud and abuse, and comply with legal obligations.</p>
        <p>We do <strong>not</strong> sell your personal information, as "sale" is defined under the CCPA/CPRA.</p>
      </>
    ),
  },
  {
    id: 'ai-processing',
    heading: 'AI Processing Disclosure',
    content: (
      <>

        <p>The Service uses artificial intelligence, including large language models, to generate resume content, scores, feedback, and recommendations.</p>
        <ul>
          <li><strong>AI outputs are estimates, not guarantees.</strong> Scores such as ATS compatibility, Hiring Readiness, or Career Health are generated from the information you provide and general market data — they do not guarantee employment outcomes, interview success, or salary results.</li>
          <li><strong>Your content is sent to AI processing providers</strong> to generate these outputs.</li>
          <li><strong>Human review is not performed on every AI output</strong> before it is shown to you, unless a specific feature states otherwise.</li>
          <li><strong>You should independently verify</strong> any AI-generated content before relying on it, including for factual accuracy.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'legal-bases',
    heading: 'Legal Bases for Processing (GDPR/UK GDPR)',
    content: (
      <>
        <p>If you are located in the EEA or UK, we rely on the following legal bases:</p>
        <table>
          <thead><tr><th>Purpose</th><th>Legal Basis</th></tr></thead>
          <tbody>
            <tr><td>Providing the Service</td><td>Performance of a contract</td></tr>
            <tr><td>AI-generated career analysis</td><td>Performance of a contract / Consent, where required</td></tr>
            <tr><td>Marketing communications</td><td>Consent</td></tr>
            <tr><td>Fraud prevention and security</td><td>Legitimate interests</td></tr>
            <tr><td>Legal compliance</td><td>Legal obligation</td></tr>
          </tbody>
        </table>
        <p>You may withdraw consent at any time where processing is based on consent, without affecting the lawfulness of processing carried out before withdrawal.</p>
      </>
    ),
  },
  {
    id: 'cookies',
    heading: 'Cookies and Tracking Technologies',
    content: <p>We use cookies and similar technologies to operate and improve the Service. Full detail on the categories of cookies we use and how to manage your preferences is provided in our separate Cookie Policy, which forms part of this Privacy Policy by reference.</p>,
  },
  {
    id: 'how-we-share',
    heading: 'How We Share Your Information',
    content: (
      <>
        <p>We share personal information only with service providers who process data on our behalf (hosting, database, AI processing, payment processing, email delivery), where required to comply with a legal obligation or governmental request, in connection with a business transfer such as a merger or acquisition, or where you direct us to.</p>
        <p>We do not share your resume content, assessment answers, or interview responses with employers or recruiters unless you take an affirmative, explicit action to do so.</p>
      </>
    ),
  },
  {
    id: 'data-retention',
    heading: 'Data Retention',
    content: (
      <>
        <table>
          <thead><tr><th>Data Type</th><th>Retention Approach</th></tr></thead>
          <tbody>
            <tr><td>Account information</td><td>Retained while your account is active; deleted within 90 days of account deletion, subject to legal retention requirements</td></tr>
            <tr><td>Resume and assessment data</td><td>Retained while your account is active; deleted within 90 days of account deletion or a specific deletion request</td></tr>
            <tr><td>Payment records</td><td>Retained as required by applicable Indian tax and financial recordkeeping law, which may exceed 90 days</td></tr>
            <tr><td>Server/security logs</td><td>Retained for 90 days for security purposes</td></tr>
          </tbody>
        </table>
      </>
    ),
  },
  {
    id: 'data-security',
    heading: 'Data Security',
    content: <p>We implement technical and organizational measures designed to protect your information, including encryption in transit, access controls, and secure infrastructure practices. However, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.</p>,
  },
  {
    id: 'international-transfers',
    heading: 'International Data Transfers',
    content: <p>Your information may be transferred to, and processed in, countries other than the country in which you reside. Where required, we rely on appropriate safeguards such as Standard Contractual Clauses to protect your information during such transfers.</p>,
  },
  {
    id: 'your-rights',
    heading: 'Your Privacy Rights',
    content: (
      <>
        <p><strong>Under GDPR / UK GDPR</strong>, you have the right to access, rectify, erase, restrict processing, port your data, object to processing, withdraw consent, and lodge a complaint with your local data protection authority.</p>
        <p><strong>Under India's DPDP Act</strong>, you have the right to access a summary of your data and processing activities, correction and erasure, grievance redressal through our Grievance Officer, nomination of another individual to exercise your rights on your behalf, and withdrawal of consent at any time.</p>
        <p><strong>Under CCPA/CPRA (California)</strong>, you have the right to know, delete, and correct your personal information, opt out of sale or sharing (we do not sell personal information), limit use of sensitive data, and non-discrimination for exercising these rights.</p>
        <p>You can exercise most of these rights directly within your account settings, or by contacting us at <strong>info@earngro.app</strong>. We will respond within the timeframe required by applicable law.</p>
      </>
    ),
  },
  {
    id: 'childrens-privacy',
    heading: "Children's Privacy",
    content: <p>The Service is not directed at, and is not intended for use by, individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected personal information from a child without appropriate consent, we will take steps to delete that information.</p>,
  },
  {
    id: 'third-party-services',
    heading: 'Third-Party Services',
    content: <p>We use third-party service providers for cloud hosting and database (Supabase), AI processing, payment processing, and email delivery. Each provider processes data under its own privacy terms and, where applicable, a data processing agreement with us.</p>,
  },
  {
    id: 'changes',
    heading: 'Changes to This Policy',
    content: <p>We may update this Privacy Policy from time to time. If we make material changes, we will notify you via the Service or by email before the changes take effect.</p>,
  },
  {
    id: 'contact',
    heading: 'Contact Us',
    content: (
      <>
        <p><strong>EarnGro</strong><br />1108-10, Tower-1, Assotech Business Cresterra, Sector 135, Noida 201304, India<br />Email: info@earngro.app<br />Website: www.earngro.app</p>
        <p><strong>Grievance Officer (India DPDP Act):</strong> [Name / Email to be appointed — required under the DPDP Act before publication]</p>
      </>
    ),
  },
]

export default function PrivacyPage() {
  return <LegalDocLayout title="Privacy Policy" effectiveDate="August 2, 2026" sections={sections} />
}